DEVOPS-5650: final for release

diff --git a/bt/settings b/bt/settings
--- a/bt/settings
+++ b/bt/settings
@@ -1,98 +1,170 @@
 #!/usr/bin/env /usr/local/bin/bash
 # shellcheck disable=SC2148,SC2034
-# ----------------------------------------------
-# Behavioral settings for components in bintools. 
+# -----------------------------------------------------------------
 
-# loader.sh - NOTE: We set LOADER_ACTIVE to avoid 
-# being fodder for the meat grinder....  
+# -----------------------------------------------------------------
+# DEBUGGING
+# -----------------------------------------------------------------
 
-export BT="${HOME}/.bt"
-
-if [[ -z "${LOADER_ACTIVE}" || "${LOADER_ACTIVE}" == false ]]; then
-
-  # loader config
-  . ${BT}/lib/loader.sh  
-  loader_addpath "${BT}/lib*"
-
-  # main script(s):
-  includex bt_load main_load
-fi
-
+# global debug function.
 to_debug() { [[ "${BT_DEBUG}" = *$1* ]] && >&2 "${@:2}" ;}
-export BT_SETTINGS=quiet 
-to_debug stgs && sleep 1 && echo stgs o
 
 # shellcheck disable=SC1090,SC1094 
 [[ "${BASH_VERSION:0:1}" -ne 5 ]] && { 
   echo "WARNING: unsupported shell spawned: ${BASH_VERSION}" && exit 1
 }
 
+#export BT_DEBUG="flow env lgin rds rdsc rdst cche util data pmpt qvdb"
+to_debug flow && sleep 0.5 && echo "stgs:debug"
+
+
+# ------------------------------------------------------------------
+# SETTINGS
+# ------------------------------------------------------------------
+
+to_debug flow && sleep 0.5 && echo "stgs:settings"
+
+# additional config settings for BT. 
+export BT=${HOME}/.bt
+export BT_SETTINGS=quiet 
+#export BT_SETTINGS=
+
+# uncomment while debugging.
+#export BT_DEBUG="env lgin rds rdsl rdsc rdst cche util data prmt qv"
+#export BT_DEBUG="rds rdsl rdsc rdst"
+
+export DEFAULT_ROLE="qventus"
+export DEFAULT_ACCOUNT="prod"
+
+# finding the proper sso-lib
+export AWSLIB="devops"
+# fall back to aws-sso-util when devops isn't available.
+[[ ! -e "${DEFAULT_AWSLIB}" ]] && { 
+    export AWSLIB="aws" 
+    export DEFAULT_AWSLIB="${HOME}/.local/bin/${AWSLIB}-sso-util" 
+} 
+
+
+# -----------------------------------------------------------------
+# ARG PARSING
+# -----------------------------------------------------------------
+
+to_debug flow && sleep 0.5 && echo "stgs:arg_parsing"
+
+account="${1:-"prod"}"
+
+
+# -----------------------------------------------------------------
+# SHELL LOADER 
+# -----------------------------------------------------------------
+
+# For loading associative arrays from files or variables.
+
+
+to_debug stgs  echo LOADER_ACTIVE: "${LOADER_ACTIVE}"
+
+. ${BT}/lib/utils.bash
+bt_loader
+
+
+
+# -----------------------------------------------------------------
+# CACHE SETTINGS
+# -----------------------------------------------------------------
+
+to_debug flow && sleep 0.5 && echo "stgs:cache"
+set_team
+
+
 # -----------------------------------------------------------------
 # PATH SETTINGS
 # -----------------------------------------------------------------
+
+to_debug flow && sleep 0.5 && echo "stgs:path"
 
 [[ ! -f "${BT}"/cache/path_info ]] && {
   to_debug stgs && sleep 1 && echo stgs:path_info
   "${BT}"/utils/path -s 2>/dev/null | tee ${BT}/cache/path_info 
 }
 
-
-to_debug stgs && sleep 1 && echo stgs:source path
+to_debug stgs && sleep 1 && echo stgs:source_path
 source <(echo "$("${BT}"/utils/path -s 2>/dev/null)" )
 
-
 # -----------------------------------------------------------------
-# ALIASES
+# ESSENTIAL ALIASES
 # -----------------------------------------------------------------
 
-poetry="$(which poetry)"
-alias ssm_cmpl="src/ssm_cmpl"
-alias ssm="poetry run poe ssm_cmpl && poetry run poe ssm ${@}"
+to_debug flow && sleep 0.5 && echo "stgs:aliases"
 
-alias rds="poetry run poe rds_cmpl && poetry run poe rds ${@}"
-alias rds_term="poetry run poe rds_cmpl && poetry run poe rds ${@}"
-alias dg="poetry run poe rds_cmpl && poetry run poe dg ${@}"
+#poetry="$(which poetry)"
 
-to_debug stgs && sleep 1 && echo stgs:aliases
+# ssm tool.
+#alias ssm_cmpl=". ${BT}/src/ssm.cmpl"
+#alias ssm="ssm_cmpl; poetry run poe ssm ${@}"
+
+# rds tool.
+#alias rds_cmpl=". ${BT}/src/rds.cmpl"
+#alias rds="rds_cmpl; poetry run poe rds ${@}"
+
+# other.
+#alias rds_term="poetry run poe rds_cmpl && poetry run poe rds ${@}"
+#alias dg="poetry run poe rds_cmpl && poetry run poe dg ${@}"
+
+
 
 # -----------------------------------------------------------------
 # ENV SETTINGS
 # -----------------------------------------------------------------
 
-[[ -e "${HOME}/.bt/.iterm2_shell_integration.bash" ]] && { 
-  source "${HOME}/.iterm2_shell_integration.bash"
-}
+to_debug flow && sleep 0.5 && echo "stgs:env"
 
-env_init
+# scripted shell activation (experimental).
+#[[ -e "${HOME}/.bt/.iterm2_shell_integration.bash" ]] && { 
+#  source "${HOME}/.iterm2_shell_integration.bash"
+#}
 
-to_debug stgs && sleep 1 && echo stgs 
+# defaults should be generated by the loader.
+to_debug stgs && echo stgs:env BT_TEAM   : ${BT_TEAM} 
+to_debug stgs && echo stgs:env BT_ACCOUNT: ${BT_ACCOUNT} 
+to_debug stgs && echo stgs:env BT_ROLE:    ${BT_ROLE}
 
-# -----------------------------------------------------------------
-# AWS LOGIN
-# -----------------------------------------------------------------
 
-# autologin 
 
 # -----------------------------------------------------------------
 # Bootstrap functions.
 # -----------------------------------------------------------------
 
-#JSON="{\"account\":{\"prod\":${ACCT_ID}} | jq -r -c '.account | to_entries[] | select(.key|tostring) | "\(.key)"'"
-#echo "prod" |  jq -r '.account | to_entries[] | select(.key|tostring) | "\(.key)"'
+to_debug flow && sleep 0.5 && echo "stgs:bootstrap_funcs"
 
-to_debug stgs && sleep 1 && echo stgs VV
+
+
+
+# -----------------------------------------------------------------
+# AWS LOGIN
+# -----------------------------------------------------------------
+
+to_debug flow && sleep 0.5 && echo "stgs:autologin"
+
+# Uncomment this if you want logins to happen 
+# through settings.  Team account defaults to prod, for now.
+# autologin "${account}" 
+
+
+
+
 
 # ------------------------------------------------------------------
-# SETTINGS
+# load bintools functions, customizations, completions.
 # ------------------------------------------------------------------
-# config settings for BT. 
 
-# ------------------------------------------------------------------
-# load bintools libraries.
-# ------------------------------------------------------------------
+to_debug flow && sleep 0.5 && echo "stgs:sources"
+
+role=qventus 
+[[ -n "${BT_ROLE}" ]] && { role="${BT_ROLE}" ;}
+autologin $role 
 
 q() {  
-  
+ : 
   # ----------------------------------------------------------------
   # GENERATORS 
   # ----------------------------------------------------------------
@@ -103,83 +175,60 @@ q() {
   # SOURCING
   # ----------------------------------------------------------------
   # Bintools does a lot of sourcing to create a productive environment. 
-  # To be effective, sourced files cannot be used from within a subshell, 
-  # command block, or function. 
   #
   # Globbing
   # --------
   # Advanced globbing is an easy way to sort through files. 
-  # But we need to Keep tabs on whether a particular glob was 
-  # originally set.  We should only toggle the setting if 
-  # originally not set.
   # 
-  shopt -q extglob;     extglob_set=$?
-  shopt -q nullglob;    nullglob_set=$?
-  shopt -q dotglob;     dotglob_set=$?
-  shopt -q nocasematch; nocasematch_set=$?
- 
-  ((extglob_set))     && shopt -s extglob
-  ((nullglob_set))    && shopt -s nullglob
-  ((dotglob_set))     && shopt -s dotglob
-  ((nocasematch_set)) && shopt -s nocasematchglob
+  #shopt -q extglob;     extglob_set=$?
+  #((extglob_set))     && shopt -s extglob
 
-  # SOURCE FILES, e.g. bash_completions, settings, functions, 
-  # aliases, etc.  We source these in the current context, 
-  # no functions or subshells.
-  
   # Array of dirs where source files live.
   # As a rule, these are sourced ONLY from here, and ONLY once.
-  declare -a dirs
-  dirs=(           \
-    src            \
-    src/generate.d \
-  )                
+#  declare -a dirs
+#  dirs=(           \
+#    src            \
+#  )                
+#
+#  for d in $(printf "%s\n" "${dirs[@]}"); do
+#    # sources dirs only. 
+#    [[ "${d}" = src* ]] || continue  
+#    DIR="${BT}/${d}" && q_pushd 2>/dev/null "${DIR}"
+#    echo -ne "\n\n${BLUE}Sourcing in ${DIR}...${NC}\n\n"
+#    # shellcheck disable=SC2125
+#    glob=[!_]?*
+#    files=( "$( printf "%s\n" "${glob}")" )
+# 
+#    # longest file. 
+#    lg=0
+#    for f in $(printf '%s' "${files[@]}"); do 
+#      this=${#f}
+#      [[ "$lg" -le "$this" ]] && lg=$this 
+#    done
+# 
+#    for f in $(printf '%s' "${files[@]}"); do
+#      [[ ${f} = *.@(new|cmpl|src|gen|arr$) ]] || continue
+#      src_str="\t./${f}"
+#      # shellcheck disable=SC1090,SC1094 
+#      source ./"${f}" >/dev/null 2>&1    && \
+#      status="success!" COLOR="${GREEN}" || \
+#      status="failed."  COLOR="${RED}"  
+#      printf "%b%*.b%b${COLOR}%s${NC}%b\n"  \
+#          "$src_str" $(( lg - "${#f}" + 10 )) "."30 "" "${status}"
+#    done
+#    # shellcheck disable=SC2119
+#    q_popd && "echo thanks!"
+#  done
+#
+#  echo _____ 
 
-  for d in $(printf "%s\n" "${dirs[@]}"); do
-    # sources dirs only. 
-    [[ "${d}" = src* ]] || continue  
-    DIR="${BT}/${d}" && q_pushd "${DIR}"
-    echo -ne "\n\n${BLUE}Sourcing in ${DIR}...${NC}\n\n"
-    # shellcheck disable=SC2125
-    glob=[!_]?*
-    files=( "$( printf "%s\n" "${glob}")" )
- 
-    # longest file. 
-    lg=0
-    for f in $(printf '%s' "${files[@]}"); do 
-      this=${#f}
-      [[ "$lg" -le "$this" ]] && lg=$this 
-    done
- 
-    for f in $(printf '%s' "${files[@]}"); do
-      [[ ${f} = *.@(new|cmpl|src|gen|arr$) ]] || continue
-      src_str="\t./${f}"
-      # shellcheck disable=SC1090,SC1094 
-      source ./"${f}" >/dev/null 2>&1 &&    \
-      status="success!" COLOR="${GREEN}" || \
-      status="failed." COLOR="${RED}"
-      printf "%b%*.b%b${COLOR}%s${NC}%b\n"  \
-          "$src_str" $(( lg - "${#f}" + 10 )) "."30 "" "${status}"
-    done
-    # shellcheck disable=SC2119
-    q_popd 
-  done
-
-  echo _____ 
-
-  # Toggle extglob & nullglob if they were not originally set.
-  # NOTE: The 0 (true) from shopt -q above is (false) in a an 
-  # arithmetic context (as below). 
-  ((extglob_set))     && shopt -u extglob
-  ((nullglob_set))    && shopt -u nullglob
-  ((dotglob_set))     && shopt -u dotglob
-  ((nocasematch_set)) && shopt -u nocasematch
-  echo -ne "\n\n\n"
+#  ((extglob_set))     && shopt -u extglob
+#  echo -ne "\n\n\n"
   
   # For fun, show a pretty tree-based display.  
-  tree -a -C "${BT}"/src --noreport --dirsfirst -F
+#  tree -a -C "${BT}"/src --noreport --dirsfirst -F
 }
 
 # shellcheck disable=SC2015
-[[ "${BT_SETTINGS}" =~ quiet ]] && q > /dev/null 2>&1 || q
+#[[ "${BT_SETTINGS}" = *quiet* ]] && q > /dev/null 2>&1 || q
 
